version: "3"
services: 
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=000000
      - POSTGRES_USER=postgres
      - POSTGRES_DB=asa_tb1
  api:
    depends_on: 
      - "db"
    restart: on-failure
    build: .
    ports:
      - "3333:3333"
    links:
      - "db"
    command: npm start

