version: "3"
services: 
  api:
    restart: always
    build: .
    environment:
      - PORT=3333
    command: npm start
    ports:
      - "3333:3333"
    links: 
      - db
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=000000
      - POSTGRES_USER=postgres
      - POSTGRES_DB=asa_tb1

